kind: PersistentVolume
apiVersion: v1
metadata:
  name: zad2-pv
  labels:
      type: local
spec:
  storageClassName: zad2
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/repodata"
